### ISSUE TITLE
cpu 调多低才能不死机 

### ISSUE THREAD

**Issue by 19950520** [ryuunoakaihitomi/xmr-miner-executable-for-raspberrypi-3b#1]
RT  加了风扇依旧死

**Comment by 19950520** [comment]
没注意电源 插在路由器usb口上了
![image](https://user-images.githubusercontent.com/13502844/34649086-a358b98a-f3e2-11e7-91b0-aba5f979975b.png)

**Comment by ryuunoakaihitomi** [comment]
。。。。。。还有事吗
